name: CD

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  build:
    uses: ./.github/workflows/CI.yml

  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [build]
    environment: Staging
    steps:
      - name: checkout the source code
        uses: actions/checkout@v4
      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli