name: CD

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  build:
    uses: ./.github/workflows/CI.yml

  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [build]
    environment: Staging
    permissions:
      id-token: write
    
    env:
      AWS_REGION: "eu-central-1"
      APP_NAME: "swiss-geometa-validator"
      ENV_NAME: "staging"

    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Download web folder
        uses: actions/download-artifact@v4
        with:
          name: web
          path: web

      - name: Commit web folder
        run: |
          git config --global user.name "CD Build Artifacts"
          git config --global user.email "action@github.com"
          git add -f web
          git commit -m "commit web folder for AWS EB CLI"

      # - name: Install EB CLI
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install awsebcli

      # - name: Configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: ${{env.AWS_REGION}}
      #     role-to-assume: arn:aws:iam::789590757708:role/github-swiss-geometa-validator

      # - name: Init application
      #   run: |
      #     eb init ${{env.APP_NAME}} -r ${{env.AWS_REGION}} -p 'Docker running on 64bit Amazon Linux 2023'

      # - name: Create application
      #   run: |
      #     eb create ${{env.APP_NAME}}-${{env.ENV_NAME}} -s

      # - name: Deploy application
      #   if: always()
      #   run: |
      #     eb deploy ${{env.APP_NAME}}-${{env.ENV_NAME}}
